title: "Petr Simecek"
description: "Bioinformatics Analyst, The Jackson Laboratory"
about: "R RStudio Shiny Tidyverse Python Kaggle Github Running Kids"
location: "Bar Harbor, Maine, USA"
email: 
baseurl: ""

url: "http://simecek.github.io" # replace by your site's url
github_username:  simecek
twitter_username: simecek42
linkedin_username: petr.simecek
linkedin: petr.simecek
author: "Petr Simecek"

# google analytics tracking code, please change the value
g_analytics: "UA-90647482-1"

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Blog"
posts_btn: "Twitter"
middle_btn: "Too short to post, too long to tweet"

imprint_btn: ""
name_badge: ""
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# exclude files
exclude:
  - LICENSE
  - README.md
